### ISSUE TITLE
npm not functioning in Cloud IDE

### ISSUE THREAD

**Issue by lgbridges** [Washington-County/COUNTY-DRUPAL#306]
Wonder if this is happening in Lando/DDEV. I am unable to run npm commands to rebuild theme.

```
Error: ENOENT: no such file or directory, uv_cwd
    at process.wrappedCwd (internal/bootstrap/switches/does_own_process_state.js:128:26)
    at process.cwd (/home/ide/.nvm/versions/node/v12.22.1/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:10:19)
    at Conf.loadPrefix (/home/ide/.nvm/versions/node/v12.22.1/lib/node_modules/npm/lib/config/load-prefix.js:46:24)
    at load_ (/home/ide/.nvm/versions/node/v12.22.1/lib/node_modules/npm/lib/config/core.js:109:8)
    at Conf.<anonymous> (/home/ide/.nvm/versions/node/v12.22.1/lib/node_modules/npm/lib/config/core.js:96:5)
    at Conf.emit (events.js:314:20)
    at ConfigChain._resolve (/home/ide/.nvm/versions/node/v12.22.1/lib/node_modules/npm/node_modules/config-chain/index.js:281:34)
    at ConfigChain.add (/home/ide/.nvm/versions/node/v12.22.1/lib/node_modules/npm/node_modules/config-chain/index.js:259:10)
    at Conf.add (/home/ide/.nvm/versions/node/v12.22.1/lib/node_modules/npm/lib/config/core.js:338:27)
    at Conf.<anonymous> (/home/ide/.nvm/versions/node/v12.22.1/lib/node_modules/npm/lib/config/core.js:314:25)
internal/bootstrap/switches/does_own_process_state.js:128
  cachedCwd = rawMethods.cwd();
                         ^

Error: ENOENT: no such file or directory, uv_cwd
    at process.wrappedCwd (internal/bootstrap/switches/does_own_process_state.js:128:26)
    at process.cwd (/home/ide/.nvm/versions/node/v12.22.1/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:10:19)
    at process.errorHandler (/home/ide/.nvm/versions/node/v12.22.1/lib/node_modules/npm/lib/utils/error-handler.js:183:30)
    at process.emit (events.js:314:20)
    at process._fatalException (internal/process/execution.js:165:25) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'uv_cwd'
}
```

**Comment by jlwcor** [comment]
Can you share what command you are running and in what directory?

`blt custom:theme:build` should work and I'm having no issues on my end in IDE.

**Comment by lgbridges** [comment]
I am trying to do `npm run production` or `npm run watch` in the westy theme folder.

**Comment by lgbridges** [comment]
Totally works now. No idea what changed. Closing.
